---
title: "echan_ex3.4: Calculating Sharpe Ratio for Long-Only Versus Market-Neutral Strategies"
author: "Austin Haffenden"
date: '`r Sys.Date()`'
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example 3.5:
```{r ex3_5}
library(pracma)
calculateMaxDD <- function(cumret) {
  
  # initialise highwatermark to zero
  highwatermark <- rep(0, length(cumret))
  
  # initialize drawdowns to zero
  drawdown <- rep(0, length(cumret))
  
  # initialize drawdown duration to zero
  drawdownduration <- rep(0, length(cumret))

  for(t in 2:length(cumret)) {
    
    highwatermark[t] <- max(highwatermark[t-1], cumret[t])
  
    # drawdown on each day
    #drawdown[t] <- (1+cumret[t])/(1+highwatermark[t])-1
    drawdown[t] <- mrdivide((1+cumret[t]), (1+highwatermark[t]))-1
    
    if (drawdown[t]==0) {
        drawdownduration[t] <- 0
    } else {
        drawdownduration[t] <- drawdownduration[t-1]+1
    }
  }

  # maximum drawdown
  maxDD <- min(drawdown)

  # maximum drawdown duration
  maxDDD <- max(drawdownduration)

  return(c(maxDD, maxDDD))
}
calculateMaxDD(cumret)

# Assume this is a continuation of the above MATLAB
# code.

# cumulative compounded returns
cumret <- cumprod(1+netRet)-1
plot(cumret)


out <- calculateMaxDD(cumret)

# [maxDrawdown maxDrawdownDuration]=...
# calculateMaxDD(cumret);
# # maximum drawdown. Output should be 0.1053
# maxDrawdown
# # maximum drawdown duration. Output should be 497.
# maxDrawdownDuration

# Notice the code fragment above calls a function “calculateMaxDrawdown,”
# which I display below
```
