---
title: "echan_box6.1: Finding correlations between returns of different time frames"
author: "Austin Haffenden"
date: '`r Sys.Date()`'
output: 
  md_document:
    variant: markdown_github
---

##Finding correlations between returns of different time frames

```{r cl_libs}
rm(list = ls())
detach(package:echanFuncs, unload = TRUE)
library(echanFuncs)
library(R.matlab)
library(pracma)
library(vrtest)

```

```{r data_in}
list.files("data")
data_in <- readMat("data/inputDataOHLCDaily_20120511.mat")
str(data_in)

syms <- data_in$syms
tday <- data_in$tday
cl <- data_in$cl

idx <- match("TU", unlist(syms))

tday <- tday[, idx];
cl <- cl[, idx];

```

## The correlation tests

```{r corr_tests}

out_dat <- data.frame(lookback = NA, holddays = NA, cc = NA, pval = NA)

for (lookback in c(1, 5, 10, 25, 60, 120, 250)) {
    for (holddays in c(1, 5, 10, 25, 60, 120, 250)) {
      
        ret_lag <- (cl-backshift(lookback, cl))/backshift(lookback, cl)
        ret_fut <- (fwdshift(holddays, cl)-cl)/cl

        # badDates=any([isnan(ret_lag) isnan(ret_fut)], 2);
        badDates <- ifelse(is.na(ret_lag)|is.na(ret_fut),1,0 )
        # ret_lag(badDates)=[];
        ret_lag <- ret_lag[badDates == 0]
        # ret_fut(badDates)=[];
        ret_fut <- ret_fut[badDates == 0]
        
        if (lookback >= holddays) {
          indepSet <- seq(1, length(ret_lag), holddays)
        } else {
          indepSet <- seq(1, length(ret_lag), lookback)
        }
        
        # ret_lag=ret_lag(indepSet);
        ret_lag <- ret_lag[indepSet]
        # ret_fut=ret_fut(indepSet);
        ret_fut <- ret_fut[indepSet]
             
        # [cc, pval]=corrcoef(ret_lag, ret_fut);
        corr_res <- cor.test(ret_lag, ret_fut)
        cc <- corr_res$estimate
        pval <- corr_res$p.value

        out_dat <- rbind(out_dat, data.frame(lookback, holddays, cc, pval))
        
  }
}
out_dat
```

```{r hurst_vratio}
# Hurst exponent and Variance ratio test
# H=genhurst(log(cl), 2);
# fprintf(1, 'H2=%f\n', H);
H = hurstexp(log(cl))

# Variance ratio test from Matlab Econometrics Toolbox
# [h,pValue]=vratiotest(log(cl));
Auto.VR(log(cl))

# fprintf(1, 'h=%i\n', h); % h=1 means rejection of random walk hypothesis, 0 means it is a random walk.
# fprintf(1, 'pValue=%f\n', pValue); % pValue is essentially the probability that the null hypothesis (random walk) is true.
```

```{r ...}
lookback <- 250
holddays <- 25

longs <- cl > backshift(lookback, cl)  
longs[is.na(longs)] <- FALSE
shorts <- cl < backshift(lookback, cl)
shorts[is.na(shorts)] <- FALSE

pos <- rep(0, length(cl))

for (h in 0:(holddays-1)) {
  print(h)
    long_lag <- backshift(h, longs)
    long_lag[is.nan(long_lag)] <- FALSE
    long_lag <- as.logical(long_lag)
    
    short_lag <- backshift(h, shorts)
    short_lag[is.nan(short_lag)] <- FALSE
    short_lag <- as.logical(short_lag)
    
    pos[long_lag] <- pos[long_lag]+1
    pos[short_lag] <- pos[short_lag]-1
}

#ret=(backshift(1, pos).*(cl-backshift(1, cl))./backshift(1, cl))/holddays;
ret <- (backshift(1, pos)*(cl-backshift(1, cl))/backshift(1, cl))/holddays

ret[is.nan(ret)] <- 0
idx <- which(tday==20090102)
# idx=1;

cumret <- cumprod(1+ret[idx:length(ret)])-1

plot(cumret)

# Avg Ann Ret = 0.0167 
# Sharpe ratio =1.04 
# APR = 0.0167
# Max DD = -0.024847 
# Max DDD in days = 343
# Kelly f = 64.919535


# Avg Ann Ret: 252*smartmean(ret(idx:end))
# Ann Volatility: sqrt(252)*smartstd(ret(idx:end))
# Sharpe ratio: sqrt(252)*smartmean(ret(idx:end))/smartstd(ret(idx:end)));
# APR: prod(1+ret(idx:end)).^(252/length(ret(idx:end)))-1)
# maxDDD: calculateMaxDD(cumret)
# maxDD: round(maxDDD))
# Kelly: mean(ret(idx:end))/std(ret(idx:end))^2)



```
